### ISSUE TITLE
Custody services v3

### ISSUE THREAD

**Issue by FabianRuti** [OpenWealth/OpenWealth#10]
Regarding the new endpoints, is there a reason for adding these? Which TPPs will implement?

**Comment by andiahlm** [comment]
@FabianRuti Thanks for raising the question. Most TPPs we have spoken to would prefer a resource oriented endpoint structure - query lists of transactions & positions by params as well as single positions and transactions by id - instead of querying statements. This will also simplify the process of amendments (for example correction of prices, valuation of a transaction or position). Does this answer the question?
