### ISSUE TITLE
Order Placement - ExpiryDateTime

### ISSUE THREAD

**Issue by chiny123** [OpenWealth/OpenWealth#115]
**Submitted by: Fabian Rutishauser - ZKB
Date: 22.03.2023**

Even though this is theoretically a timestamp field. We only interpret the date and use the respective end-of-day (23:59:59). How do other participants interpret this field?

**Comment by MichaelWuestSGKB** [comment]
SGKB basically has the same interpretation. An ExpiryDate would be sufficient for us. (at least for the current use cases)

**Comment by dustyush0sq** [comment]
In order to accomodate for potential foreign users in different time zones, IMHO it would make sense to consider making it a time zoned timestamp or other uniquely identifiable timestamp that would allow to translate instants from one time zone to another and, potentially, in case of day/GTD orders, adjust the timestamp to the trading hours of respective markets. 

As some venues are open 24/7 , like cryptos or FX, and in theory allow expiration times more fine grained than day,  IMHO it would make sense to keep it as timestamp in generic case.

**Comment by TLusti** [comment]
I see it similar to @dustyush0sq 
Keeping it this way, also gives us the flexibility to cater for the two usecases described above.
