### ISSUE TITLE
OP API - Notification - Enumerations description for payload extension

### ISSUE THREAD

**Issue by chiny123** [OpenWealth/OpenWealth#124]
https://github.com/OpenWealth/OpenWealth/blob/b225aee94a51e2065ce991e82b4ed7be596dda9e/OrderPlacement/Docs/Enums.md?plain=1#L1

we also need description of each payload extension fields (e.g executedQuantity, remainingQuantity, lastQuantity etc.)

**Comment by TLusti** [comment]
![image](https://github.com/user-attachments/assets/7df20e09-a674-4eb6-9fb2-00cb62fcabbe)

Hi @chiny123, attributes are normally directly described in the API itself (see picture above), which for Enumerations is unfortunately not possible. If there is the opinion, that descriptions are not sufficient, let me know, so that I can rather update it in the API specification itself, instead of having it described in a separate file. 

If ok with you, would close this issue.

**Comment by chiny123** [comment]
Hi @TLusti thanks, this issue can be closed.
