### ISSUE TITLE
Custody Services v3 - Removal of BookingDate/ValueDate on Transaction

### ISSUE THREAD

**Issue by FabianRuti** [OpenWealth/OpenWealth#9]
Why has the Array for dates on a transaction been removed. Today we send the triple of bookingDate,valueDate, transactionDate for every transaction. Now in v3 there is only a transactionDate on the transaction. This is in our opinion worse, it is unclear if we should now fill this field with the booking or transaction Date.

Additionally, the movementDate will not be different for the movements in most of the cases for securities, bonds, funds, cash etc. I understand that for otc transactions this can vary, but is it really the best solution to create this redundancy for other (more used) asset tpyes? 

https://github.com/OpenWealth/CustodyServicesMembers/blob/52450688e39c1ced1186f31a08a3566bf201532e/Specs/CustodyServices.yaml#L794C9-L794C24

**Comment by andiahlm** [comment]
@FabianRuti as extensively discussed in the circles bookingDate and valueDate should be set on the movement (where bookingDate has been renamed to movementDate). OTC business events require to set the information on movement level since business events with movements on different days are possible. The redundancy was discussed but it was preferred to not allow the information to be set in different places. Also it was discussed that the movementDate should be relevant to provide consistency with the balance of the position (sum of movements by movementDate should sum up to the balance of the position for the given date). The transactionDate should be used to determine on what date it is contained in the transaction statement. It most cases this will correspond with the movementDate. Does this answer your question?
